// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uutapwlrvqcktnvunvqc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV1dGFwd2xydnFja3RudnVudnFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQwMTA5NzgsImV4cCI6MjA0OTU4Njk3OH0.Rj4dd5_GJPHSWXnMiE6N_qOcS_Ax2vG0diFza3gwmpE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);